### ISSUE TITLE
!cookie doesn't work

### ISSUE THREAD

**Issue by LeiRoF** [Gunivers/Gipsy#51]
On some serveurs such as "CompuPhys / PICS" (885793332914159636), the !cookie command lead to an unexpected error

Traceback:
```log
Traceback (most recent call last):
   File "/home/container/.local/lib/python3.9/site-packages/i18n/loaders/yaml_loader.py", line 13, in parse_file
    return yaml.load(file_content, Loader=yaml.FullLoader)
   File "/home/container/.local/lib/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
   File "/home/container/.local/lib/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
   File "/home/container/.local/lib/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
   File "/home/container/.local/li
```

**Comment by ascpial** [comment]
Il doit y avoir un problème de formatage du fichier de traduction du plugin cookies en anglais.
Je m'occupe de ça.

**Comment by ascpial** [comment]
Apparemment soit le problème ne vient pas des fichiers de traductions soit le problème a été résolu sur la branche beta.
@LeiRoF, est-ce que tu pourrais me confirmer qu'il y a toujours un problème avec la commande sur la version beta ?
