### ISSUE TITLE
Logs : 'Member' object has no attribute 'avatar_url'

### ISSUE THREAD

**Issue by Aeris1One** [Gunivers/Gipsy#85]
```logs
Ignoring exception in on_message_edit
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.10/site-packages/nextcord/client.py", line 512, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/plugins/logs/bot/main.py", line 131, in on_message_edit
    icon_url=before.author.avatar_url)
AttributeError: 'Member' object has no attribute 'avatar_url'
```

**Comment by ascpial** [comment]
Résolu avec [#45 du repo Gipsy-plugins](https://github.com/Gunivers/Gipsy-plugins/pull/45).
