### ISSUE TITLE
Console spammed when stopping the bot

### ISSUE THREAD

**Issue by ascpial** [Gunivers/Gipsy#95]
Quand on stop le bot avec `^C`, la console envoie plusieurs fois un message du style suivant.

Il faudrait régler ce soucis qui est un peu gênant.

```
Traceback (most recent call last):
  File "/home/ascpial/Projets/Gipsy/venv/lib64/python3.11/site-packages/discord/client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/ascpial/Projets/Gipsy/venv/lib64/python3.11/site-packages/discord/client.py", line 746, in start
    await self.connect(reconnect=reconnect)
  File "/home/ascpial/Projets/Gipsy/venv/lib64/python3.11/site-packages/discord/shard.py", line 447, in connect
    item = await self.__queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ascpial/Projets/Gipsy/utils.py", line 221, in remove_cog
    module.on_anycog_unload(cog)
  File "/home/ascpial/Projets/Gipsy/bot/utils/sconfig.py", line 84, in on_anycog_unload
    self.bot.get_command("config " + opt["command"]).enabled = False
                         ~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by ascpial** [comment]
Résolu avec #115.
